[project]
name = "zpp_menu"
version = "1.3.1"
description = "Générateur d'un menu à touches fléchées"
mainfile = "__init__.py"
requires-python = ">=3.6"

[project.metadata]
authors = ["ZephyrOff"]
maintainers = []
readme = "README.md"
license = "MIT License"
license_file = "LICENSE"
keywords = ["menu","terminal","zephyroff"]
classifiers = ["Development Status :: 5 - Production/Stable", "Environment :: Console", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3"]
copyright = ""
changelog = "changelog.md"

[project.urls]
changelog = ""
homepage = "https://github.com/ZephyrOff/zpp_menu"
documentation = "https://github.com/ZephyrOff/zpp_menu"

[project.dependencies]

[project.dependencies.windows]

[project.dependencies.linux]

[project.build]
packages = []
includes = ["menu"]
excludes = []
include_files = []
optimize = 0
no_compress = false
GUI = false
icon = ""

[project.wheel]
platforms = "ALL"

[project.wheel.entry_points]
console_scripts = []
